<div class=" col-xs-12">
<form role="form" method="GET">
	<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Nome</label>
		<input type="email" class="form-control" id="nome" />
	</div>

		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Modelo/ano</label>
		<input type="email" class="form-control" id="modeloAno" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Marca</label>
		<input type="email" class="form-control" id="marca" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Placa</label>
		<input type="email" class="form-control" id="placa" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Categoria</label>
		<input type="email" class="form-control" id="categoria" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Chaci</label>
		<input type="email" class="form-control" id="chaci" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Renavam</label>
		<input type="email" class="form-control" id="renavam" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Cor</label>
		<input type="email" class="form-control" id="cor" />
	</div>
		<div class="form-group col-md-4">
		 
		<label for="exampleInputEmail1">Valor</label>
		<input type="email" class="form-control" id="valor" />
	</div>
	<div class="form-group col-md-4"> 
		<label for="exampleInputEmail1">Kilometragem</label>
		<input type="email" class="form-control" id="kilometragem" />
	</div>
		
	<div class="form-group col-md-4">
		<label for="sel1">Combustivel</label> 
		<select name="Categoria"
			class="form-control">
			<option value="Gasolina">Gasolina</option>
			<option value="Alcool">Álcool</option>
			<option value="Diesel">Diesel</option>
			<option value="Flex">Flex</option>
		</select>
	</div>
	
	<div class="form-group col-md-4">
		 
		<label for="exampleInputFile">
			Imagem
		</label>
		<input type="file" id="exampleInputFile" />
		<p class="help-block">
			Escolha uma imagem para o veículo.
		</p>
	</div>
	<div class="form-group col-md-4">
	&nbsp;&nbsp;&nbsp;<button href="?id=cadastrarVeiculo" class="btn btn-primary">
		cadastrar
	</button></a>
	<button type="" class="btn btn-warning ">
		Limpar
	</button>
	</div>
</form>
</div>
